# Generated by Django 2.0 on 2021-12-07 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_question_question_opt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_opt',
        ),
    ]
