# Generated by Django 2.0 on 2021-12-17 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_question_sino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='sino',
        ),
    ]
