# Generated by Django 2.0 on 2021-12-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_remove_question_sino'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='preferencia',
            field=models.BooleanField(default=False),
        ),
    ]
