# Generated by Django 2.0 on 2021-12-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_auto_20211212_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='question',
        ),
        migrations.AddField(
            model_name='voting',
            name='question',
            field=models.ManyToManyField(related_name='voting', to='voting.Question'),
        ),
    ]
