# Generated by Django 2.0 on 2022-01-08 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_auto_20211219_0922'),
        ('voting', '0005_auto_20211221_1615'),
    ]

    operations = [
    ]
